require_relative '../node_modules/react-native/scripts/react_native_pods'
require_relative '../node_modules/@react-native-community/cli-platform-ios/native_modules'

platform :ios, '11.0'
target 'suidaga' do

rn_path = '../node_modules/react-native'
rn_maps_path = '../node_modules/react-native-maps'

# react-native-maps dependencies
pod 'react-native-maps', path: rn_maps_path
pod 'react-native-google-maps', path: rn_maps_path  # Uncomment this line if you want to support GoogleMaps on iOS
pod 'GoogleMaps'  # Uncomment this line if you want to support GoogleMaps on iOS
pod 'Google-Maps-iOS-Utils' # Uncomment this line if you want to support GoogleMaps on iOS
  config = use_native_modules!

  use_react_native!(
    :path => config[:reactNativePath],
    # to enable hermes on iOS, change `false` to `true` and then install pods
    :hermes_enabled => false
  )

  # pod 'RNGoogleSignin', :path => '../node_modules/@react-native-google-signin/google-signin'

  # pod 'react-native-stripe-payments', :path => '../node_modules/react-native-stripe-payments'

  target 'suidagaTests' do
    inherit! :complete
    # Pods for testing
  end

  # Enables Flipper.
  #
  # Note that if you have use_frameworks! enabled, Flipper will not work and
  # you should disable the next line.
  # use_flipper!({ 'Flipper' => '0.108.0' })
  use_flipper!({'Flipper' => '0.92.0', 'Flipper-Folly' => '2.6.7'})

   post_install do |installer|
     react_native_post_install(installer)
   end
   
end
